### ISSUE TITLE
Wrong kunena 4.x themes url in xml and html sitemap

### ISSUE THREAD

**Issue by remotehelp** [b2un0/joomla-component-mapx#1]
If in plugin "Xmap - Kunena Integration" settings "Show themes" set to "On" then in sitemap links generate as "/component/kunena/cat-name/theme-name" instead  "/kunena-alias/cat-name/theme-name instead" - "kunena-alias" meaning alias that set in menu manager for kunena menu.

**Comment by b2un0** [comment]
Project has discontinued.
